[build]
  base = "client"
  publish = "client/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://your-backend-api-url.com"
  VITE_STRIPE_KEY = "pk_live_your_key"
  VITE_TURN_SERVER = "turn:turn.tabla.mk"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
