[build]
  base = "client/src"
  publish = "client/src/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://your-backend-url.com"
  VITE_STRIPE_KEY = "pk_live_..."
  VITE_TURN_SERVER = "turn:turn.tabla.mk"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
